export const FONTS = [
  { label: 'Antonio', value: 'antonio' },
  { label: 'Arimo', value: 'arimo' },
  { label: 'Cousine', value: 'cousine' },
  { label: 'Digital_7', value: 'digital_7' },
  { label: 'EB_Garamond', value: 'eb_garamond' },
  { label: 'Foldit', value: 'foldit' },
  { label: 'Handjet', value: 'handjet' },
  { label: 'IBM_Plex_Mono', value: 'ibm_plex_mono' },
  { label: 'IBM_Plex_Sans', value: 'ibm_plex_sans' },
  { label: 'Noto_Sans_Mono', value: 'noto_sans_mono' },
  { label: 'Radio_Canada', value: 'radio_canada' },
  { label: 'Red_Hat_Mono', value: 'red_hat_mono' },
  { label: 'Roboto', value: 'roboto' },
  { label: 'Roboto_Mono', value: 'roboto_mono' },
];
