export const SIZES = [
  { label: '1X', value: '1rem' },
  { label: '2X', value: '2rem' },
  { label: '3X', value: '3rem' },
  { label: '4X', value: '4rem' },
  { label: '5X', value: '5rem' },
  { label: '6X', value: '6rem' },
  { label: '7X', value: '7rem' },
  { label: '8X', value: '8rem' },
  { label: '9X', value: '9rem' },
  { label: '10X', value: '10rem' },
  { label: '15X', value: '15rem' },
  { label: '20X', value: '20rem' },
  { label: '25X', value: '25rem' },
  { label: '30X', value: '30rem' },
  { label: '35X', value: '35rem' },
  { label: '40X', value: '40rem' },
  { label: '45X', value: '45rem' },
  { label: '50X', value: '50rem' },
  { label: '60X', value: '60rem' },
  { label: '70X', value: '70rem' },
  { label: '80X', value: '80rem' },
  { label: '90X', value: '90rem' },
  { label: '100X', value: '100rem' },
];
