export const TIMEZONES = [
  { value: 'Etc/GMT+12', label: '(GMT-12:00) GMT+12' },
  { value: 'Etc/GMT+11', label: '(GMT-11:00) GMT+11' },
  { value: 'Pacific/Midway', label: '(GMT-11:00) Midway' },
  { value: 'Pacific/Niue', label: '(GMT-11:00) Niue' },
  { value: 'Pacific/Pago_Pago', label: '(GMT-11:00) Pago Pago' },
  { value: 'Pacific/Samoa', label: '(GMT-11:00) Samoa' },
  { value: 'US/Samoa', label: '(GMT-11:00) Samoa' },
  { value: 'Etc/GMT+10', label: '(GMT-10:00) GMT+10' },
  { value: 'HST', label: '(GMT-10:00) HST' },
  { value: 'Pacific/Honolulu', label: '(GMT-10:00) Honolulu' },
  { value: 'Pacific/Johnston', label: '(GMT-10:00) Johnston' },
  { value: 'Pacific/Rarotonga', label: '(GMT-10:00) Rarotonga' },
  { value: 'Pacific/Tahiti', label: '(GMT-10:00) Tahiti' },
  { value: 'US/Hawaii', label: '(GMT-10:00) Hawaii' },
  { value: 'Pacific/Marquesas', label: '(GMT-09:30) Marquesas' },
  { value: 'America/Adak', label: '(GMT-09:00) Adak' },
  { value: 'America/Atka', label: '(GMT-09:00) Atka' },
  { value: 'Etc/GMT+9', label: '(GMT-09:00) GMT+9' },
  { value: 'Pacific/Gambier', label: '(GMT-09:00) Gambier' },
  { value: 'US/Aleutian', label: '(GMT-09:00) Aleutian' },
  { value: 'America/Anchorage', label: '(GMT-08:00) Anchorage' },
  { value: 'America/Juneau', label: '(GMT-08:00) Juneau' },
  { value: 'America/Metlakatla', label: '(GMT-08:00) Metlakatla' },
  { value: 'America/Nome', label: '(GMT-08:00) Nome' },
  { value: 'America/Sitka', label: '(GMT-08:00) Sitka' },
  { value: 'America/Yakutat', label: '(GMT-08:00) Yakutat' },
  { value: 'Etc/GMT+8', label: '(GMT-08:00) GMT+8' },
  { value: 'Pacific/Pitcairn', label: '(GMT-08:00) Pitcairn' },
  { value: 'US/Alaska', label: '(GMT-08:00) Alaska' },
  { value: 'America/Creston', label: '(GMT-07:00) Creston' },
  { value: 'America/Dawson', label: '(GMT-07:00) Dawson' },
  { value: 'America/Dawson_Creek', label: '(GMT-07:00) Dawson Creek' },
  { value: 'America/Ensenada', label: '(GMT-07:00) Ensenada' },
  { value: 'America/Fort_Nelson', label: '(GMT-07:00) Fort Nelson' },
  { value: 'America/Hermosillo', label: '(GMT-07:00) Hermosillo' },
  { value: 'America/Los_Angeles', label: '(GMT-07:00) Los Angeles' },
  { value: 'America/Mazatlan', label: '(GMT-07:00) Mazatlan' },
  { value: 'America/Phoenix', label: '(GMT-07:00) Phoenix' },
  { value: 'America/Santa_Isabel', label: '(GMT-07:00) Santa Isabel' },
  { value: 'America/Tijuana', label: '(GMT-07:00) Tijuana' },
  { value: 'America/Vancouver', label: '(GMT-07:00) Vancouver' },
  { value: 'America/Whitehorse', label: '(GMT-07:00) Whitehorse' },
  { value: 'Canada/Pacific', label: '(GMT-07:00) Pacific' },
  { value: 'Canada/Yukon', label: '(GMT-07:00) Yukon' },
  { value: 'Etc/GMT+7', label: '(GMT-07:00) GMT+7' },
  { value: 'MST', label: '(GMT-07:00) MST' },
  { value: 'Mexico/BajaNorte', label: '(GMT-07:00) BajaNorte' },
  { value: 'Mexico/BajaSur', label: '(GMT-07:00) BajaSur' },
  { value: 'PST8PDT', label: '(GMT-07:00) PST8PDT' },
  { value: 'US/Arizona', label: '(GMT-07:00) Arizona' },
  { value: 'US/Pacific', label: '(GMT-07:00) Pacific' },
  { value: 'America/Bahia_Banderas', label: '(GMT-06:00) Bahia Banderas' },
  { value: 'America/Belize', label: '(GMT-06:00) Belize' },
  { value: 'America/Boise', label: '(GMT-06:00) Boise' },
  { value: 'America/Cambridge_Bay', label: '(GMT-06:00) Cambridge Bay' },
  { value: 'America/Chihuahua', label: '(GMT-06:00) Chihuahua' },
  { value: 'America/Ciudad_Juarez', label: '(GMT-06:00) Ciudad Juarez' },
  { value: 'America/Costa_Rica', label: '(GMT-06:00) Costa Rica' },
  { value: 'America/Denver', label: '(GMT-06:00) Denver' },
  { value: 'America/Edmonton', label: '(GMT-06:00) Edmonton' },
  { value: 'America/El_Salvador', label: '(GMT-06:00) El Salvador' },
  { value: 'America/Guatemala', label: '(GMT-06:00) Guatemala' },
  { value: 'America/Inuvik', label: '(GMT-06:00) Inuvik' },
  { value: 'America/Managua', label: '(GMT-06:00) Managua' },
  { value: 'America/Merida', label: '(GMT-06:00) Merida' },
  { value: 'America/Mexico_City', label: '(GMT-06:00) Mexico City' },
  { value: 'America/Monterrey', label: '(GMT-06:00) Monterrey' },
  { value: 'America/Regina', label: '(GMT-06:00) Regina' },
  { value: 'America/Shiprock', label: '(GMT-06:00) Shiprock' },
  { value: 'America/Swift_Current', label: '(GMT-06:00) Swift Current' },
  { value: 'America/Tegucigalpa', label: '(GMT-06:00) Tegucigalpa' },
  { value: 'America/Yellowknife', label: '(GMT-06:00) Yellowknife' },
  { value: 'Canada/Mountain', label: '(GMT-06:00) Mountain' },
  { value: 'Canada/Saskatchewan', label: '(GMT-06:00) Saskatchewan' },
  { value: 'Chile/EasterIsland', label: '(GMT-06:00) EasterIsland' },
  { value: 'Etc/GMT+6', label: '(GMT-06:00) GMT+6' },
  { value: 'MST7MDT', label: '(GMT-06:00) MST7MDT' },
  { value: 'Mexico/General', label: '(GMT-06:00) General' },
  { value: 'Navajo', label: '(GMT-06:00) Navajo' },
  { value: 'Pacific/Easter', label: '(GMT-06:00) Easter' },
  { value: 'Pacific/Galapagos', label: '(GMT-06:00) Galapagos' },
  { value: 'US/Mountain', label: '(GMT-06:00) Mountain' },
  { value: 'America/Atikokan', label: '(GMT-05:00) Atikokan' },
  { value: 'America/Bogota', label: '(GMT-05:00) Bogota' },
  { value: 'America/Cancun', label: '(GMT-05:00) Cancun' },
  { value: 'America/Cayman', label: '(GMT-05:00) Cayman' },
  { value: 'America/Chicago', label: '(GMT-05:00) Chicago' },
  { value: 'America/Coral_Harbour', label: '(GMT-05:00) Coral Harbour' },
  { value: 'America/Eirunepe', label: '(GMT-05:00) Eirunepe' },
  { value: 'America/Guayaquil', label: '(GMT-05:00) Guayaquil' },
  { value: 'America/Indiana/Knox', label: '(GMT-05:00) Indiana' },
  { value: 'America/Indiana/Tell_City', label: '(GMT-05:00) Indiana' },
  { value: 'America/Jamaica', label: '(GMT-05:00) Jamaica' },
  { value: 'America/Knox_IN', label: '(GMT-05:00) Knox IN' },
  { value: 'America/Lima', label: '(GMT-05:00) Lima' },
  { value: 'America/Matamoros', label: '(GMT-05:00) Matamoros' },
  { value: 'America/Menominee', label: '(GMT-05:00) Menominee' },
  { value: 'America/North_Dakota/Beulah', label: '(GMT-05:00) North Dakota' },
  { value: 'America/North_Dakota/Center', label: '(GMT-05:00) North Dakota' },
  { value: 'America/North_Dakota/New_Salem', label: '(GMT-05:00) North Dakota' },
  { value: 'America/Ojinaga', label: '(GMT-05:00) Ojinaga' },
  { value: 'America/Panama', label: '(GMT-05:00) Panama' },
  { value: 'America/Porto_Acre', label: '(GMT-05:00) Porto Acre' },
  { value: 'America/Rainy_River', label: '(GMT-05:00) Rainy River' },
  { value: 'America/Rankin_Inlet', label: '(GMT-05:00) Rankin Inlet' },
  { value: 'America/Resolute', label: '(GMT-05:00) Resolute' },
  { value: 'America/Rio_Branco', label: '(GMT-05:00) Rio Branco' },
  { value: 'America/Winnipeg', label: '(GMT-05:00) Winnipeg' },
  { value: 'Brazil/Acre', label: '(GMT-05:00) Acre' },
  { value: 'CST6CDT', label: '(GMT-05:00) CST6CDT' },
  { value: 'Canada/Central', label: '(GMT-05:00) Central' },
  { value: 'EST', label: '(GMT-05:00) EST' },
  { value: 'Etc/GMT+5', label: '(GMT-05:00) GMT+5' },
  { value: 'Jamaica', label: '(GMT-05:00) Jamaica' },
  { value: 'US/Central', label: '(GMT-05:00) Central' },
  { value: 'US/Indiana-Starke', label: '(GMT-05:00) Indiana-Starke' },
  { value: 'America/Anguilla', label: '(GMT-04:00) Anguilla' },
  { value: 'America/Antigua', label: '(GMT-04:00) Antigua' },
  { value: 'America/Aruba', label: '(GMT-04:00) Aruba' },
  { value: 'America/Asuncion', label: '(GMT-04:00) Asuncion' },
  { value: 'America/Barbados', label: '(GMT-04:00) Barbados' },
  { value: 'America/Blanc-Sablon', label: '(GMT-04:00) Blanc-Sablon' },
  { value: 'America/Boa_Vista', label: '(GMT-04:00) Boa Vista' },
  { value: 'America/Campo_Grande', label: '(GMT-04:00) Campo Grande' },
  { value: 'America/Caracas', label: '(GMT-04:00) Caracas' },
  { value: 'America/Cuiaba', label: '(GMT-04:00) Cuiaba' },
  { value: 'America/Curacao', label: '(GMT-04:00) Curacao' },
  { value: 'America/Detroit', label: '(GMT-04:00) Detroit' },
  { value: 'America/Dominica', label: '(GMT-04:00) Dominica' },
  { value: 'America/Fort_Wayne', label: '(GMT-04:00) Fort Wayne' },
  { value: 'America/Grand_Turk', label: '(GMT-04:00) Grand Turk' },
  { value: 'America/Grenada', label: '(GMT-04:00) Grenada' },
  { value: 'America/Guadeloupe', label: '(GMT-04:00) Guadeloupe' },
  { value: 'America/Guyana', label: '(GMT-04:00) Guyana' },
  { value: 'America/Havana', label: '(GMT-04:00) Havana' },
  { value: 'America/Indiana/Indianapolis', label: '(GMT-04:00) Indiana' },
  { value: 'America/Indiana/Marengo', label: '(GMT-04:00) Indiana' },
  { value: 'America/Indiana/Petersburg', label: '(GMT-04:00) Indiana' },
  { value: 'America/Indiana/Vevay', label: '(GMT-04:00) Indiana' },
  { value: 'America/Indiana/Vincennes', label: '(GMT-04:00) Indiana' },
  { value: 'America/Indiana/Winamac', label: '(GMT-04:00) Indiana' },
  { value: 'America/Indianapolis', label: '(GMT-04:00) Indianapolis' },
  { value: 'America/Iqaluit', label: '(GMT-04:00) Iqaluit' },
  { value: 'America/Kentucky/Louisville', label: '(GMT-04:00) Kentucky' },
  { value: 'America/Kentucky/Monticello', label: '(GMT-04:00) Kentucky' },
  { value: 'America/Kralendijk', label: '(GMT-04:00) Kralendijk' },
  { value: 'America/La_Paz', label: '(GMT-04:00) La Paz' },
  { value: 'America/Louisville', label: '(GMT-04:00) Louisville' },
  { value: 'America/Lower_Princes', label: '(GMT-04:00) Lower Princes' },
  { value: 'America/Manaus', label: '(GMT-04:00) Manaus' },
  { value: 'America/Marigot', label: '(GMT-04:00) Marigot' },
  { value: 'America/Martinique', label: '(GMT-04:00) Martinique' },
  { value: 'America/Montreal', label: '(GMT-04:00) Montreal' },
  { value: 'America/Montserrat', label: '(GMT-04:00) Montserrat' },
  { value: 'America/Nassau', label: '(GMT-04:00) Nassau' },
  { value: 'America/New_York', label: '(GMT-04:00) New York' },
  { value: 'America/Nipigon', label: '(GMT-04:00) Nipigon' },
  { value: 'America/Pangnirtung', label: '(GMT-04:00) Pangnirtung' },
  { value: 'America/Port-au-Prince', label: '(GMT-04:00) Port-au-Prince' },
  { value: 'America/Port_of_Spain', label: '(GMT-04:00) Port of Spain' },
  { value: 'America/Porto_Velho', label: '(GMT-04:00) Porto Velho' },
  { value: 'America/Puerto_Rico', label: '(GMT-04:00) Puerto Rico' },
  { value: 'America/Santiago', label: '(GMT-04:00) Santiago' },
  { value: 'America/Santo_Domingo', label: '(GMT-04:00) Santo Domingo' },
  { value: 'America/St_Barthelemy', label: '(GMT-04:00) St Barthelemy' },
  { value: 'America/St_Kitts', label: '(GMT-04:00) St Kitts' },
  { value: 'America/St_Lucia', label: '(GMT-04:00) St Lucia' },
  { value: 'America/St_Thomas', label: '(GMT-04:00) St Thomas' },
  { value: 'America/St_Vincent', label: '(GMT-04:00) St Vincent' },
  { value: 'America/Thunder_Bay', label: '(GMT-04:00) Thunder Bay' },
  { value: 'America/Toronto', label: '(GMT-04:00) Toronto' },
  { value: 'America/Tortola', label: '(GMT-04:00) Tortola' },
  { value: 'America/Virgin', label: '(GMT-04:00) Virgin' },
  { value: 'Brazil/West', label: '(GMT-04:00) West' },
  { value: 'Canada/Eastern', label: '(GMT-04:00) Eastern' },
  { value: 'Chile/Continental', label: '(GMT-04:00) Continental' },
  { value: 'Cuba', label: '(GMT-04:00) Cuba' },
  { value: 'EST5EDT', label: '(GMT-04:00) EST5EDT' },
  { value: 'Etc/GMT+4', label: '(GMT-04:00) GMT+4' },
  { value: 'US/East-Indiana', label: '(GMT-04:00) East-Indiana' },
  { value: 'US/Eastern', label: '(GMT-04:00) Eastern' },
  { value: 'US/Michigan', label: '(GMT-04:00) Michigan' },
  { value: 'America/Araguaina', label: '(GMT-03:00) Araguaina' },
  { value: 'America/Argentina/Buenos_Aires', label: '(GMT-03:00) Argentina' },
  { value: 'America/Argentina/Catamarca', label: '(GMT-03:00) Argentina' },
  { value: 'America/Argentina/ComodRivadavia', label: '(GMT-03:00) Argentina' },
  { value: 'America/Argentina/Cordoba', label: '(GMT-03:00) Argentina' },
  { value: 'America/Argentina/Jujuy', label: '(GMT-03:00) Argentina' },
  { value: 'America/Argentina/La_Rioja', label: '(GMT-03:00) Argentina' },
  { value: 'America/Argentina/Mendoza', label: '(GMT-03:00) Argentina' },
  { value: 'America/Argentina/Rio_Gallegos', label: '(GMT-03:00) Argentina' },
  { value: 'America/Argentina/Salta', label: '(GMT-03:00) Argentina' },
  { value: 'America/Argentina/San_Juan', label: '(GMT-03:00) Argentina' },
  { value: 'America/Argentina/San_Luis', label: '(GMT-03:00) Argentina' },
  { value: 'America/Argentina/Tucuman', label: '(GMT-03:00) Argentina' },
  { value: 'America/Argentina/Ushuaia', label: '(GMT-03:00) Argentina' },
  { value: 'America/Bahia', label: '(GMT-03:00) Bahia' },
  { value: 'America/Belem', label: '(GMT-03:00) Belem' },
  { value: 'America/Buenos_Aires', label: '(GMT-03:00) Buenos Aires' },
  { value: 'America/Catamarca', label: '(GMT-03:00) Catamarca' },
  { value: 'America/Cayenne', label: '(GMT-03:00) Cayenne' },
  { value: 'America/Cordoba', label: '(GMT-03:00) Cordoba' },
  { value: 'America/Fortaleza', label: '(GMT-03:00) Fortaleza' },
  { value: 'America/Glace_Bay', label: '(GMT-03:00) Glace Bay' },
  { value: 'America/Goose_Bay', label: '(GMT-03:00) Goose Bay' },
  { value: 'America/Halifax', label: '(GMT-03:00) Halifax' },
  { value: 'America/Jujuy', label: '(GMT-03:00) Jujuy' },
  { value: 'America/Maceio', label: '(GMT-03:00) Maceio' },
  { value: 'America/Mendoza', label: '(GMT-03:00) Mendoza' },
  { value: 'America/Moncton', label: '(GMT-03:00) Moncton' },
  { value: 'America/Montevideo', label: '(GMT-03:00) Montevideo' },
  { value: 'America/Paramaribo', label: '(GMT-03:00) Paramaribo' },
  { value: 'America/Punta_Arenas', label: '(GMT-03:00) Punta Arenas' },
  { value: 'America/Recife', label: '(GMT-03:00) Recife' },
  { value: 'America/Rosario', label: '(GMT-03:00) Rosario' },
  { value: 'America/Santarem', label: '(GMT-03:00) Santarem' },
  { value: 'America/Sao_Paulo', label: '(GMT-03:00) Sao Paulo' },
  { value: 'America/Thule', label: '(GMT-03:00) Thule' },
  { value: 'Antarctica/Palmer', label: '(GMT-03:00) Palmer' },
  { value: 'Antarctica/Rothera', label: '(GMT-03:00) Rothera' },
  { value: 'Atlantic/Bermuda', label: '(GMT-03:00) Bermuda' },
  { value: 'Atlantic/Stanley', label: '(GMT-03:00) Stanley' },
  { value: 'Brazil/East', label: '(GMT-03:00) East' },
  { value: 'Canada/Atlantic', label: '(GMT-03:00) Atlantic' },
  { value: 'Etc/GMT+3', label: '(GMT-03:00) GMT+3' },
  { value: 'America/St_Johns', label: '(GMT-02:30) St Johns' },
  { value: 'Canada/Newfoundland', label: '(GMT-02:30) Newfoundland' },
  { value: 'America/Miquelon', label: '(GMT-02:00) Miquelon' },
  { value: 'America/Noronha', label: '(GMT-02:00) Noronha' },
  { value: 'Atlantic/South_Georgia', label: '(GMT-02:00) South Georgia' },
  { value: 'Brazil/DeNoronha', label: '(GMT-02:00) DeNoronha' },
  { value: 'Etc/GMT+2', label: '(GMT-02:00) GMT+2' },
  { value: 'America/Godthab', label: '(GMT-01:00) Godthab' },
  { value: 'America/Nuuk', label: '(GMT-01:00) Nuuk' },
  { value: 'America/Scoresbysund', label: '(GMT-01:00) Scoresbysund' },
  { value: 'Atlantic/Cape_Verde', label: '(GMT-01:00) Cape Verde' },
  { value: 'Etc/GMT+1', label: '(GMT-01:00) GMT+1' },
  { value: 'Africa/Abidjan', label: '(GMT+00:00) Abidjan' },
  { value: 'Africa/Accra', label: '(GMT+00:00) Accra' },
  { value: 'Africa/Bamako', label: '(GMT+00:00) Bamako' },
  { value: 'Africa/Banjul', label: '(GMT+00:00) Banjul' },
  { value: 'Africa/Bissau', label: '(GMT+00:00) Bissau' },
  { value: 'Africa/Conakry', label: '(GMT+00:00) Conakry' },
  { value: 'Africa/Dakar', label: '(GMT+00:00) Dakar' },
  { value: 'Africa/Freetown', label: '(GMT+00:00) Freetown' },
  { value: 'Africa/Lome', label: '(GMT+00:00) Lome' },
  { value: 'Africa/Monrovia', label: '(GMT+00:00) Monrovia' },
  { value: 'Africa/Nouakchott', label: '(GMT+00:00) Nouakchott' },
  { value: 'Africa/Ouagadougou', label: '(GMT+00:00) Ouagadougou' },
  { value: 'Africa/Sao_Tome', label: '(GMT+00:00) Sao Tome' },
  { value: 'Africa/Timbuktu', label: '(GMT+00:00) Timbuktu' },
  { value: 'America/Danmarkshavn', label: '(GMT+00:00) Danmarkshavn' },
  { value: 'Atlantic/Azores', label: '(GMT+00:00) Azores' },
  { value: 'Atlantic/Reykjavik', label: '(GMT+00:00) Reykjavik' },
  { value: 'Atlantic/St_Helena', label: '(GMT+00:00) St Helena' },
  { value: 'Etc/GMT', label: '(GMT+00:00) GMT' },
  { value: 'Etc/GMT+0', label: '(GMT+00:00) GMT+0' },
  { value: 'Etc/GMT-0', label: '(GMT+00:00) GMT-0' },
  { value: 'Etc/GMT0', label: '(GMT+00:00) GMT0' },
  { value: 'Etc/Greenwich', label: '(GMT+00:00) Greenwich' },
  { value: 'Etc/UCT', label: '(GMT+00:00) UCT' },
  { value: 'Etc/UTC', label: '(GMT+00:00) UTC' },
  { value: 'Etc/Universal', label: '(GMT+00:00) Universal' },
  { value: 'Etc/Zulu', label: '(GMT+00:00) Zulu' },
  { value: 'GMT', label: '(GMT+00:00) GMT' },
  { value: 'GMT+0', label: '(GMT+00:00) GMT+0' },
  { value: 'GMT-0', label: '(GMT+00:00) GMT-0' },
  { value: 'GMT0', label: '(GMT+00:00) GMT0' },
  { value: 'Greenwich', label: '(GMT+00:00) Greenwich' },
  { value: 'Iceland', label: '(GMT+00:00) Iceland' },
  { value: 'UCT', label: '(GMT+00:00) UCT' },
  { value: 'UTC', label: '(GMT+00:00) UTC' },
  { value: 'Universal', label: '(GMT+00:00) Universal' },
  { value: 'Zulu', label: '(GMT+00:00) Zulu' },
  { value: 'Africa/Algiers', label: '(GMT+01:00) Algiers' },
  { value: 'Africa/Bangui', label: '(GMT+01:00) Bangui' },
  { value: 'Africa/Brazzaville', label: '(GMT+01:00) Brazzaville' },
  { value: 'Africa/Casablanca', label: '(GMT+01:00) Casablanca' },
  { value: 'Africa/Douala', label: '(GMT+01:00) Douala' },
  { value: 'Africa/El_Aaiun', label: '(GMT+01:00) El Aaiun' },
  { value: 'Africa/Kinshasa', label: '(GMT+01:00) Kinshasa' },
  { value: 'Africa/Lagos', label: '(GMT+01:00) Lagos' },
  { value: 'Africa/Libreville', label: '(GMT+01:00) Libreville' },
  { value: 'Africa/Luanda', label: '(GMT+01:00) Luanda' },
  { value: 'Africa/Malabo', label: '(GMT+01:00) Malabo' },
  { value: 'Africa/Ndjamena', label: '(GMT+01:00) Ndjamena' },
  { value: 'Africa/Niamey', label: '(GMT+01:00) Niamey' },
  { value: 'Africa/Porto-Novo', label: '(GMT+01:00) Porto-Novo' },
  { value: 'Africa/Tunis', label: '(GMT+01:00) Tunis' },
  { value: 'Atlantic/Canary', label: '(GMT+01:00) Canary' },
  { value: 'Atlantic/Faeroe', label: '(GMT+01:00) Faeroe' },
  { value: 'Atlantic/Faroe', label: '(GMT+01:00) Faroe' },
  { value: 'Atlantic/Madeira', label: '(GMT+01:00) Madeira' },
  { value: 'Eire', label: '(GMT+01:00) Eire' },
  { value: 'Etc/GMT-1', label: '(GMT+01:00) GMT-1' },
  { value: 'Europe/Belfast', label: '(GMT+01:00) Belfast' },
  { value: 'Europe/Dublin', label: '(GMT+01:00) Dublin' },
  { value: 'Europe/Guernsey', label: '(GMT+01:00) Guernsey' },
  { value: 'Europe/Isle_of_Man', label: '(GMT+01:00) Isle of Man' },
  { value: 'Europe/Jersey', label: '(GMT+01:00) Jersey' },
  { value: 'Europe/Lisbon', label: '(GMT+01:00) Lisbon' },
  { value: 'Europe/London', label: '(GMT+01:00) London' },
  { value: 'GB', label: '(GMT+01:00) GB' },
  { value: 'GB-Eire', label: '(GMT+01:00) GB-Eire' },
  { value: 'Portugal', label: '(GMT+01:00) Portugal' },
  { value: 'WET', label: '(GMT+01:00) WET' },
  { value: 'Africa/Blantyre', label: '(GMT+02:00) Blantyre' },
  { value: 'Africa/Bujumbura', label: '(GMT+02:00) Bujumbura' },
  { value: 'Africa/Cairo', label: '(GMT+02:00) Cairo' },
  { value: 'Africa/Ceuta', label: '(GMT+02:00) Ceuta' },
  { value: 'Africa/Gaborone', label: '(GMT+02:00) Gaborone' },
  { value: 'Africa/Harare', label: '(GMT+02:00) Harare' },
  { value: 'Africa/Johannesburg', label: '(GMT+02:00) Johannesburg' },
  { value: 'Africa/Juba', label: '(GMT+02:00) Juba' },
  { value: 'Africa/Khartoum', label: '(GMT+02:00) Khartoum' },
  { value: 'Africa/Kigali', label: '(GMT+02:00) Kigali' },
  { value: 'Africa/Lubumbashi', label: '(GMT+02:00) Lubumbashi' },
  { value: 'Africa/Lusaka', label: '(GMT+02:00) Lusaka' },
  { value: 'Africa/Maputo', label: '(GMT+02:00) Maputo' },
  { value: 'Africa/Maseru', label: '(GMT+02:00) Maseru' },
  { value: 'Africa/Mbabane', label: '(GMT+02:00) Mbabane' },
  { value: 'Africa/Tripoli', label: '(GMT+02:00) Tripoli' },
  { value: 'Africa/Windhoek', label: '(GMT+02:00) Windhoek' },
  { value: 'Antarctica/Troll', label: '(GMT+02:00) Troll' },
  { value: 'Arctic/Longyearbyen', label: '(GMT+02:00) Longyearbyen' },
  { value: 'Atlantic/Jan_Mayen', label: '(GMT+02:00) Jan Mayen' },
  { value: 'CET', label: '(GMT+02:00) CET' },
  { value: 'Egypt', label: '(GMT+02:00) Egypt' },
  { value: 'Etc/GMT-2', label: '(GMT+02:00) GMT-2' },
  { value: 'Europe/Amsterdam', label: '(GMT+02:00) Amsterdam' },
  { value: 'Europe/Andorra', label: '(GMT+02:00) Andorra' },
  { value: 'Europe/Belgrade', label: '(GMT+02:00) Belgrade' },
  { value: 'Europe/Berlin', label: '(GMT+02:00) Berlin' },
  { value: 'Europe/Bratislava', label: '(GMT+02:00) Bratislava' },
  { value: 'Europe/Brussels', label: '(GMT+02:00) Brussels' },
  { value: 'Europe/Budapest', label: '(GMT+02:00) Budapest' },
  { value: 'Europe/Busingen', label: '(GMT+02:00) Busingen' },
  { value: 'Europe/Copenhagen', label: '(GMT+02:00) Copenhagen' },
  { value: 'Europe/Gibraltar', label: '(GMT+02:00) Gibraltar' },
  { value: 'Europe/Kaliningrad', label: '(GMT+02:00) Kaliningrad' },
  { value: 'Europe/Ljubljana', label: '(GMT+02:00) Ljubljana' },
  { value: 'Europe/Luxembourg', label: '(GMT+02:00) Luxembourg' },
  { value: 'Europe/Madrid', label: '(GMT+02:00) Madrid' },
  { value: 'Europe/Malta', label: '(GMT+02:00) Malta' },
  { value: 'Europe/Monaco', label: '(GMT+02:00) Monaco' },
  { value: 'Europe/Oslo', label: '(GMT+02:00) Oslo' },
  { value: 'Europe/Paris', label: '(GMT+02:00) Paris' },
  { value: 'Europe/Podgorica', label: '(GMT+02:00) Podgorica' },
  { value: 'Europe/Prague', label: '(GMT+02:00) Prague' },
  { value: 'Europe/Rome', label: '(GMT+02:00) Rome' },
  { value: 'Europe/San_Marino', label: '(GMT+02:00) San Marino' },
  { value: 'Europe/Sarajevo', label: '(GMT+02:00) Sarajevo' },
  { value: 'Europe/Skopje', label: '(GMT+02:00) Skopje' },
  { value: 'Europe/Stockholm', label: '(GMT+02:00) Stockholm' },
  { value: 'Europe/Tirane', label: '(GMT+02:00) Tirane' },
  { value: 'Europe/Vaduz', label: '(GMT+02:00) Vaduz' },
  { value: 'Europe/Vatican', label: '(GMT+02:00) Vatican' },
  { value: 'Europe/Vienna', label: '(GMT+02:00) Vienna' },
  { value: 'Europe/Warsaw', label: '(GMT+02:00) Warsaw' },
  { value: 'Europe/Zagreb', label: '(GMT+02:00) Zagreb' },
  { value: 'Europe/Zurich', label: '(GMT+02:00) Zurich' },
  { value: 'Libya', label: '(GMT+02:00) Libya' },
  { value: 'MET', label: '(GMT+02:00) MET' },
  { value: 'Poland', label: '(GMT+02:00) Poland' },
  { value: 'Africa/Addis_Ababa', label: '(GMT+03:00) Addis Ababa' },
  { value: 'Africa/Asmara', label: '(GMT+03:00) Asmara' },
  { value: 'Africa/Asmera', label: '(GMT+03:00) Asmera' },
  { value: 'Africa/Dar_es_Salaam', label: '(GMT+03:00) Dar es Salaam' },
  { value: 'Africa/Djibouti', label: '(GMT+03:00) Djibouti' },
  { value: 'Africa/Kampala', label: '(GMT+03:00) Kampala' },
  { value: 'Africa/Mogadishu', label: '(GMT+03:00) Mogadishu' },
  { value: 'Africa/Nairobi', label: '(GMT+03:00) Nairobi' },
  { value: 'Antarctica/Syowa', label: '(GMT+03:00) Syowa' },
  { value: 'Asia/Aden', label: '(GMT+03:00) Aden' },
  { value: 'Asia/Amman', label: '(GMT+03:00) Amman' },
  { value: 'Asia/Baghdad', label: '(GMT+03:00) Baghdad' },
  { value: 'Asia/Bahrain', label: '(GMT+03:00) Bahrain' },
  { value: 'Asia/Beirut', label: '(GMT+03:00) Beirut' },
  { value: 'Asia/Damascus', label: '(GMT+03:00) Damascus' },
  { value: 'Asia/Famagusta', label: '(GMT+03:00) Famagusta' },
  { value: 'Asia/Gaza', label: '(GMT+03:00) Gaza' },
  { value: 'Asia/Hebron', label: '(GMT+03:00) Hebron' },
  { value: 'Asia/Istanbul', label: '(GMT+03:00) Istanbul' },
  { value: 'Asia/Jerusalem', label: '(GMT+03:00) Jerusalem' },
  { value: 'Asia/Kuwait', label: '(GMT+03:00) Kuwait' },
  { value: 'Asia/Nicosia', label: '(GMT+03:00) Nicosia' },
  { value: 'Asia/Qatar', label: '(GMT+03:00) Qatar' },
  { value: 'Asia/Riyadh', label: '(GMT+03:00) Riyadh' },
  { value: 'Asia/Tel_Aviv', label: '(GMT+03:00) Tel Aviv' },
  { value: 'EET', label: '(GMT+03:00) EET' },
  { value: 'Etc/GMT-3', label: '(GMT+03:00) GMT-3' },
  { value: 'Europe/Athens', label: '(GMT+03:00) Athens' },
  { value: 'Europe/Bucharest', label: '(GMT+03:00) Bucharest' },
  { value: 'Europe/Chisinau', label: '(GMT+03:00) Chisinau' },
  { value: 'Europe/Helsinki', label: '(GMT+03:00) Helsinki' },
  { value: 'Europe/Istanbul', label: '(GMT+03:00) Istanbul' },
  { value: 'Europe/Kiev', label: '(GMT+03:00) Kiev' },
  { value: 'Europe/Kirov', label: '(GMT+03:00) Kirov' },
  { value: 'Europe/Kyiv', label: '(GMT+03:00) Kyiv' },
  { value: 'Europe/Mariehamn', label: '(GMT+03:00) Mariehamn' },
  { value: 'Europe/Minsk', label: '(GMT+03:00) Minsk' },
  { value: 'Europe/Moscow', label: '(GMT+03:00) Moscow' },
  { value: 'Europe/Nicosia', label: '(GMT+03:00) Nicosia' },
  { value: 'Europe/Riga', label: '(GMT+03:00) Riga' },
  { value: 'Europe/Simferopol', label: '(GMT+03:00) Simferopol' },
  { value: 'Europe/Sofia', label: '(GMT+03:00) Sofia' },
  { value: 'Europe/Tallinn', label: '(GMT+03:00) Tallinn' },
  { value: 'Europe/Tiraspol', label: '(GMT+03:00) Tiraspol' },
  { value: 'Europe/Uzhgorod', label: '(GMT+03:00) Uzhgorod' },
  { value: 'Europe/Vilnius', label: '(GMT+03:00) Vilnius' },
  { value: 'Europe/Volgograd', label: '(GMT+03:00) Volgograd' },
  { value: 'Europe/Zaporozhye', label: '(GMT+03:00) Zaporozhye' },
  { value: 'Indian/Antananarivo', label: '(GMT+03:00) Antananarivo' },
  { value: 'Indian/Comoro', label: '(GMT+03:00) Comoro' },
  { value: 'Indian/Mayotte', label: '(GMT+03:00) Mayotte' },
  { value: 'Israel', label: '(GMT+03:00) Israel' },
  { value: 'Turkey', label: '(GMT+03:00) Turkey' },
  { value: 'W-SU', label: '(GMT+03:00) W-SU' },
  { value: 'Asia/Tehran', label: '(GMT+03:30) Tehran' },
  { value: 'Iran', label: '(GMT+03:30) Iran' },
  { value: 'Asia/Baku', label: '(GMT+04:00) Baku' },
  { value: 'Asia/Dubai', label: '(GMT+04:00) Dubai' },
  { value: 'Asia/Muscat', label: '(GMT+04:00) Muscat' },
  { value: 'Asia/Tbilisi', label: '(GMT+04:00) Tbilisi' },
  { value: 'Asia/Yerevan', label: '(GMT+04:00) Yerevan' },
  { value: 'Etc/GMT-4', label: '(GMT+04:00) GMT-4' },
  { value: 'Europe/Astrakhan', label: '(GMT+04:00) Astrakhan' },
  { value: 'Europe/Samara', label: '(GMT+04:00) Samara' },
  { value: 'Europe/Saratov', label: '(GMT+04:00) Saratov' },
  { value: 'Europe/Ulyanovsk', label: '(GMT+04:00) Ulyanovsk' },
  { value: 'Indian/Mahe', label: '(GMT+04:00) Mahe' },
  { value: 'Indian/Mauritius', label: '(GMT+04:00) Mauritius' },
  { value: 'Indian/Reunion', label: '(GMT+04:00) Reunion' },
  { value: 'Asia/Kabul', label: '(GMT+04:30) Kabul' },
  { value: 'Antarctica/Mawson', label: '(GMT+05:00) Mawson' },
  { value: 'Antarctica/Vostok', label: '(GMT+05:00) Vostok' },
  { value: 'Asia/Almaty', label: '(GMT+05:00) Almaty' },
  { value: 'Asia/Aqtau', label: '(GMT+05:00) Aqtau' },
  { value: 'Asia/Aqtobe', label: '(GMT+05:00) Aqtobe' },
  { value: 'Asia/Ashgabat', label: '(GMT+05:00) Ashgabat' },
  { value: 'Asia/Ashkhabad', label: '(GMT+05:00) Ashkhabad' },
  { value: 'Asia/Atyrau', label: '(GMT+05:00) Atyrau' },
  { value: 'Asia/Dushanbe', label: '(GMT+05:00) Dushanbe' },
  { value: 'Asia/Karachi', label: '(GMT+05:00) Karachi' },
  { value: 'Asia/Oral', label: '(GMT+05:00) Oral' },
  { value: 'Asia/Qostanay', label: '(GMT+05:00) Qostanay' },
  { value: 'Asia/Qyzylorda', label: '(GMT+05:00) Qyzylorda' },
  { value: 'Asia/Samarkand', label: '(GMT+05:00) Samarkand' },
  { value: 'Asia/Tashkent', label: '(GMT+05:00) Tashkent' },
  { value: 'Asia/Yekaterinburg', label: '(GMT+05:00) Yekaterinburg' },
  { value: 'Etc/GMT-5', label: '(GMT+05:00) GMT-5' },
  { value: 'Indian/Kerguelen', label: '(GMT+05:00) Kerguelen' },
  { value: 'Indian/Maldives', label: '(GMT+05:00) Maldives' },
  { value: 'Asia/Calcutta', label: '(GMT+05:30) Calcutta' },
  { value: 'Asia/Colombo', label: '(GMT+05:30) Colombo' },
  { value: 'Asia/Kolkata', label: '(GMT+05:30) Kolkata' },
  { value: 'Asia/Kathmandu', label: '(GMT+05:45) Kathmandu' },
  { value: 'Asia/Katmandu', label: '(GMT+05:45) Katmandu' },
  { value: 'Asia/Bishkek', label: '(GMT+06:00) Bishkek' },
  { value: 'Asia/Dacca', label: '(GMT+06:00) Dacca' },
  { value: 'Asia/Dhaka', label: '(GMT+06:00) Dhaka' },
  { value: 'Asia/Kashgar', label: '(GMT+06:00) Kashgar' },
  { value: 'Asia/Omsk', label: '(GMT+06:00) Omsk' },
  { value: 'Asia/Thimbu', label: '(GMT+06:00) Thimbu' },
  { value: 'Asia/Thimphu', label: '(GMT+06:00) Thimphu' },
  { value: 'Asia/Urumqi', label: '(GMT+06:00) Urumqi' },
  { value: 'Etc/GMT-6', label: '(GMT+06:00) GMT-6' },
  { value: 'Indian/Chagos', label: '(GMT+06:00) Chagos' },
  { value: 'Asia/Rangoon', label: '(GMT+06:30) Rangoon' },
  { value: 'Asia/Yangon', label: '(GMT+06:30) Yangon' },
  { value: 'Indian/Cocos', label: '(GMT+06:30) Cocos' },
  { value: 'Antarctica/Davis', label: '(GMT+07:00) Davis' },
  { value: 'Asia/Bangkok', label: '(GMT+07:00) Bangkok' },
  { value: 'Asia/Barnaul', label: '(GMT+07:00) Barnaul' },
  { value: 'Asia/Ho_Chi_Minh', label: '(GMT+07:00) Ho Chi Minh' },
  { value: 'Asia/Hovd', label: '(GMT+07:00) Hovd' },
  { value: 'Asia/Jakarta', label: '(GMT+07:00) Jakarta' },
  { value: 'Asia/Krasnoyarsk', label: '(GMT+07:00) Krasnoyarsk' },
  { value: 'Asia/Novokuznetsk', label: '(GMT+07:00) Novokuznetsk' },
  { value: 'Asia/Novosibirsk', label: '(GMT+07:00) Novosibirsk' },
  { value: 'Asia/Phnom_Penh', label: '(GMT+07:00) Phnom Penh' },
  { value: 'Asia/Pontianak', label: '(GMT+07:00) Pontianak' },
  { value: 'Asia/Saigon', label: '(GMT+07:00) Saigon' },
  { value: 'Asia/Tomsk', label: '(GMT+07:00) Tomsk' },
  { value: 'Asia/Vientiane', label: '(GMT+07:00) Vientiane' },
  { value: 'Etc/GMT-7', label: '(GMT+07:00) GMT-7' },
  { value: 'Indian/Christmas', label: '(GMT+07:00) Christmas' },
  { value: 'Antarctica/Casey', label: '(GMT+08:00) Casey' },
  { value: 'Asia/Brunei', label: '(GMT+08:00) Brunei' },
  { value: 'Asia/Choibalsan', label: '(GMT+08:00) Choibalsan' },
  { value: 'Asia/Chongqing', label: '(GMT+08:00) Chongqing' },
  { value: 'Asia/Chungking', label: '(GMT+08:00) Chungking' },
  { value: 'Asia/Harbin', label: '(GMT+08:00) Harbin' },
  { value: 'Asia/Hong_Kong', label: '(GMT+08:00) Hong Kong' },
  { value: 'Asia/Irkutsk', label: '(GMT+08:00) Irkutsk' },
  { value: 'Asia/Kuala_Lumpur', label: '(GMT+08:00) Kuala Lumpur' },
  { value: 'Asia/Kuching', label: '(GMT+08:00) Kuching' },
  { value: 'Asia/Macao', label: '(GMT+08:00) Macao' },
  { value: 'Asia/Macau', label: '(GMT+08:00) Macau' },
  { value: 'Asia/Makassar', label: '(GMT+08:00) Makassar' },
  { value: 'Asia/Manila', label: '(GMT+08:00) Manila' },
  { value: 'Asia/Shanghai', label: '(GMT+08:00) Shanghai' },
  { value: 'Asia/Singapore', label: '(GMT+08:00) Singapore' },
  { value: 'Asia/Taipei', label: '(GMT+08:00) Taipei' },
  { value: 'Asia/Ujung_Pandang', label: '(GMT+08:00) Ujung Pandang' },
  { value: 'Asia/Ulaanbaatar', label: '(GMT+08:00) Ulaanbaatar' },
  { value: 'Asia/Ulan_Bator', label: '(GMT+08:00) Ulan Bator' },
  { value: 'Australia/Perth', label: '(GMT+08:00) Perth' },
  { value: 'Australia/West', label: '(GMT+08:00) West' },
  { value: 'Etc/GMT-8', label: '(GMT+08:00) GMT-8' },
  { value: 'Hongkong', label: '(GMT+08:00) Hongkong' },
  { value: 'PRC', label: '(GMT+08:00) PRC' },
  { value: 'ROC', label: '(GMT+08:00) ROC' },
  { value: 'Singapore', label: '(GMT+08:00) Singapore' },
  { value: 'Australia/Eucla', label: '(GMT+08:45) Eucla' },
  { value: 'Asia/Chita', label: '(GMT+09:00) Chita' },
  { value: 'Asia/Dili', label: '(GMT+09:00) Dili' },
  { value: 'Asia/Jayapura', label: '(GMT+09:00) Jayapura' },
  { value: 'Asia/Khandyga', label: '(GMT+09:00) Khandyga' },
  { value: 'Asia/Pyongyang', label: '(GMT+09:00) Pyongyang' },
  { value: 'Asia/Seoul', label: '(GMT+09:00) Seoul' },
  { value: 'Asia/Tokyo', label: '(GMT+09:00) Tokyo' },
  { value: 'Asia/Yakutsk', label: '(GMT+09:00) Yakutsk' },
  { value: 'Etc/GMT-9', label: '(GMT+09:00) GMT-9' },
  { value: 'Japan', label: '(GMT+09:00) Japan' },
  { value: 'Pacific/Palau', label: '(GMT+09:00) Palau' },
  { value: 'ROK', label: '(GMT+09:00) ROK' },
  { value: 'Australia/Adelaide', label: '(GMT+09:30) Adelaide' },
  { value: 'Australia/Broken_Hill', label: '(GMT+09:30) Broken Hill' },
  { value: 'Australia/Darwin', label: '(GMT+09:30) Darwin' },
  { value: 'Australia/North', label: '(GMT+09:30) North' },
  { value: 'Australia/South', label: '(GMT+09:30) South' },
  { value: 'Australia/Yancowinna', label: '(GMT+09:30) Yancowinna' },
  { value: 'Antarctica/DumontDUrville', label: '(GMT+10:00) DumontDUrville' },
  { value: 'Antarctica/Macquarie', label: '(GMT+10:00) Macquarie' },
  { value: 'Asia/Ust-Nera', label: '(GMT+10:00) Ust-Nera' },
  { value: 'Asia/Vladivostok', label: '(GMT+10:00) Vladivostok' },
  { value: 'Australia/ACT', label: '(GMT+10:00) ACT' },
  { value: 'Australia/Brisbane', label: '(GMT+10:00) Brisbane' },
  { value: 'Australia/Canberra', label: '(GMT+10:00) Canberra' },
  { value: 'Australia/Currie', label: '(GMT+10:00) Currie' },
  { value: 'Australia/Hobart', label: '(GMT+10:00) Hobart' },
  { value: 'Australia/Lindeman', label: '(GMT+10:00) Lindeman' },
  { value: 'Australia/Melbourne', label: '(GMT+10:00) Melbourne' },
  { value: 'Australia/NSW', label: '(GMT+10:00) NSW' },
  { value: 'Australia/Queensland', label: '(GMT+10:00) Queensland' },
  { value: 'Australia/Sydney', label: '(GMT+10:00) Sydney' },
  { value: 'Australia/Tasmania', label: '(GMT+10:00) Tasmania' },
  { value: 'Australia/Victoria', label: '(GMT+10:00) Victoria' },
  { value: 'Etc/GMT-10', label: '(GMT+10:00) GMT-10' },
  { value: 'Pacific/Chuuk', label: '(GMT+10:00) Chuuk' },
  { value: 'Pacific/Guam', label: '(GMT+10:00) Guam' },
  { value: 'Pacific/Port_Moresby', label: '(GMT+10:00) Port Moresby' },
  { value: 'Pacific/Saipan', label: '(GMT+10:00) Saipan' },
  { value: 'Pacific/Truk', label: '(GMT+10:00) Truk' },
  { value: 'Pacific/Yap', label: '(GMT+10:00) Yap' },
  { value: 'Australia/LHI', label: '(GMT+10:30) LHI' },
  { value: 'Australia/Lord_Howe', label: '(GMT+10:30) Lord Howe' },
  { value: 'Asia/Magadan', label: '(GMT+11:00) Magadan' },
  { value: 'Asia/Sakhalin', label: '(GMT+11:00) Sakhalin' },
  { value: 'Asia/Srednekolymsk', label: '(GMT+11:00) Srednekolymsk' },
  { value: 'Etc/GMT-11', label: '(GMT+11:00) GMT-11' },
  { value: 'Pacific/Bougainville', label: '(GMT+11:00) Bougainville' },
  { value: 'Pacific/Efate', label: '(GMT+11:00) Efate' },
  { value: 'Pacific/Guadalcanal', label: '(GMT+11:00) Guadalcanal' },
  { value: 'Pacific/Kosrae', label: '(GMT+11:00) Kosrae' },
  { value: 'Pacific/Norfolk', label: '(GMT+11:00) Norfolk' },
  { value: 'Pacific/Noumea', label: '(GMT+11:00) Noumea' },
  { value: 'Pacific/Pohnpei', label: '(GMT+11:00) Pohnpei' },
  { value: 'Pacific/Ponape', label: '(GMT+11:00) Ponape' },
  { value: 'Antarctica/McMurdo', label: '(GMT+12:00) McMurdo' },
  { value: 'Antarctica/South_Pole', label: '(GMT+12:00) South Pole' },
  { value: 'Asia/Anadyr', label: '(GMT+12:00) Anadyr' },
  { value: 'Asia/Kamchatka', label: '(GMT+12:00) Kamchatka' },
  { value: 'Etc/GMT-12', label: '(GMT+12:00) GMT-12' },
  { value: 'Kwajalein', label: '(GMT+12:00) Kwajalein' },
  { value: 'NZ', label: '(GMT+12:00) NZ' },
  { value: 'Pacific/Auckland', label: '(GMT+12:00) Auckland' },
  { value: 'Pacific/Fiji', label: '(GMT+12:00) Fiji' },
  { value: 'Pacific/Funafuti', label: '(GMT+12:00) Funafuti' },
  { value: 'Pacific/Kwajalein', label: '(GMT+12:00) Kwajalein' },
  { value: 'Pacific/Majuro', label: '(GMT+12:00) Majuro' },
  { value: 'Pacific/Nauru', label: '(GMT+12:00) Nauru' },
  { value: 'Pacific/Tarawa', label: '(GMT+12:00) Tarawa' },
  { value: 'Pacific/Wake', label: '(GMT+12:00) Wake' },
  { value: 'Pacific/Wallis', label: '(GMT+12:00) Wallis' },
  { value: 'NZ-CHAT', label: '(GMT+12:45) NZ-CHAT' },
  { value: 'Pacific/Chatham', label: '(GMT+12:45) Chatham' },
  { value: 'Etc/GMT-13', label: '(GMT+13:00) GMT-13' },
  { value: 'Pacific/Apia', label: '(GMT+13:00) Apia' },
  { value: 'Pacific/Enderbury', label: '(GMT+13:00) Enderbury' },
  { value: 'Pacific/Fakaofo', label: '(GMT+13:00) Fakaofo' },
  { value: 'Pacific/Kanton', label: '(GMT+13:00) Kanton' },
  { value: 'Pacific/Tongatapu', label: '(GMT+13:00) Tongatapu' },
  { value: 'Etc/GMT-14', label: '(GMT+14:00) GMT-14' },
  { value: 'Pacific/Kiritimati', label: '(GMT+14:00) Kiritimati' },
];
