version: '3.9'

services:
  web:
    container_name: cttm_web
    image: cttm_web
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./src:/app
    ports:
      - 3000:3000
    command: sh -c "pnpm start --host 0.0.0.0 --port 3000"
